### ISSUE TITLE
About Fps

### ISSUE THREAD

**Issue by tmac21** [fairbird/RaedQuickSignal#35]
Hello, Can you add channel FPS on this program ? And also setting of Signal / Quality. For Openpli 8.3 and Openatv 6.x to 7,x

**Comment by fairbird** [comment]
What channel you mean about (FPS) ?! Give me some example !!
About Signal / Quality already in plugin if does not work with youn then issue from image version you need to change version !

**Comment by fairbird** [comment]
Add screenshot please !!

**Comment by tmac21** [comment]
https://www.tunisia-sat.com/forums/attachments/1928553/   look the middle of the pic and you can see fps : 25

**Comment by fairbird** [comment]
Ok .. I got  it 
That need more extra converter file like 
https://github.com/fairbird/enigma2-dreambox/blob/develop/lib/python/Components/Converter/ServiceInfoEX.py#L60

It is not important feature .. so I don't know If I add it in next version or not. Because plugin include more than 8 skins need to edit to add that feature !! I will see when I have time if I add it or not !

**Comment by fairbird** [comment]
@tmac21
Ok .. I got it.
That calling (Framerate) already plugin have it in some screen such as ...

![1](https://github.com/fairbird/RaedQuickSignal/assets/1761779/2afc74b5-df58-4b32-aca4-f4dae26e0dbe)

![2](https://github.com/fairbird/RaedQuickSignal/assets/1761779/9514ebbe-6ccc-4b25-a8ef-c6e4554f71fe)
